schema_version: 1

context:
  name: python-msilib
  version: "0.5.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name|replace("-", "_") }}-${{ version }}.tar.gz
  sha256: 5d9d0c2af2cafbc50d484cce4cfab1cb8cfd65d705d7111d216bc525a059113b
  patches:
    - py310.patch

build:
  number: 2
  script: python -m pip install . -vv --no-deps --no-build-isolation
  skip: not win

requirements:
  build:
    - ${{ compiler("c") }}
    - ${{ stdlib("c") }}
  host:
    - python
    - pip
    - setuptools >=78.1.1,<=82
  run:
    - python

tests:
  - python:
      imports:
        - msilib
  - files:
      source:
        - pyproject.toml
        - tests
    requirements:
      run:
        - coverage >=7.10.3
        - pytest
    script:
      - coverage run

about:
  license: PSF-2.0
  license_file: LICENSE
  summary: Read and write Microsoft Installer files.
  description: |
    This library is legacy code borrowed from Python 3.12, intended to allow
    cx_Freeze's bdist_msi command to continue working in Python 3.13+. 
  homepage: https://github.com/marcelotduarte/python-msilib
  documentation: https://docs.python.org/3.12/library/msilib.html

extra:
  recipe-maintainers:
    - marcelotduarte
